typecheck::
	atscc  arrays-and-matrices.dats
	atscc  ATS-and-C.dats
	atscc  ats-main.dats
	atscc  basics.dats -lm
	atscc  dataprops.dats
	atscc  datatypes.dats
	atscc  dataviews.dats
	atscc  dataviewtypes.dats
	atscc  functions-with-variable-arguments.dats
	atscc  lazy-evaluation.dats
	atscc  pattern-matching
	atscc  programming-with-theorem-proving.dats
	atscc  references.dats
	atscc  input-and-output.dats
	atscc  tail-recursive-functions.dats
	atscc  termination-metrics.dats

######

clean::
	rm -f a.out *_dats.c *_sats.c *~

cleanall: clean; rm -f *_?ats.html

######
