#
#
# Makefile for some ProjectEuler problems
#
#

######

ATSHOMEQ=$(or "$(ATSHOME)", "/usr")
ATSCC=$(ATSHOMEQ)/bin/atscc

######

all:: checkall

######

checkall: compall cleanall
compall:: \
  problem1 \
  problem2 \
  problem3 \
  problem4 \
  problem5 \
  problem6 \
  problem7 \
  problem8 \
  problem9 \
  problem10 \
  problem11 \
  problem12 \
  problem13 \
  problem14 \
  problem15 \
  problem16 \
  problem17 \
  problem18 \
  problem19 \
  problem20 \
  problem21 \
  problem22 \
  problem23 \
  problem24 \
  problem25 \
  problem26 \
  problem27 \
  problem28 \
  problem29 \
  problem30 \
  problem31 \
  problem32 \
  problem33 \
  problem34 \
  problem35 \
  problem36 \
  problem37 \
  problem38 \
  problem39 \
  problem40 \
  problem41 \
  problem42 \
  problem43 \
  problem44 \
  problem45 \
  problem46 \
  problem47 \
  problem48 \
  problem49 \
  problem50 \
  problem51 \
  problem52 \
  problem55 \
  problem56 \
  problem57 \
  problem63 \
  problem65 \
  problem69 \
  problem71 \
  problem73 \
  problem75 \
  problem80 \
  problem92 \
  problem94 \
  problem97 \
  problem100 \
  problem104 \
  problem108 \
  problem110 \
  problem145 \
  problem157 \
  problem162 \
  problem164 \
  problem169 \
  problem301 \

######

problem1::; make -C PE-problem1 compall
problem2::; make -C PE-problem2 compall
problem3::; make -C PE-problem3 compall
problem4::; make -C PE-problem4 compall
problem5::; make -C PE-problem5 compall
problem6::; make -C PE-problem6 compall
problem7::; make -C PE-problem7 compall
problem8::; make -C PE-problem8 compall
problem9::; make -C PE-problem9 compall
problem10::; make -C PE-problem10 compall

problem11::; make -C PE-problem11 compall
problem12::; make -C PE-problem12 compall
problem13::; make -C PE-problem13 compall
problem14::; make -C PE-problem14 compall
problem15::; make -C PE-problem15 compall
problem16::; make -C PE-problem16 compall
problem17::; make -C PE-problem17 compall
problem18::; make -C PE-problem18 compall
problem19::; make -C PE-problem19 compall
problem20::; make -C PE-problem20 compall

problem21::; make -C PE-problem21 compall
problem22::; make -C PE-problem22 compall
problem23::; make -C PE-problem23 compall
problem24::; make -C PE-problem24 compall
problem25::; make -C PE-problem25 compall
problem26::; make -C PE-problem26 compall
problem27::; make -C PE-problem27 compall
problem28::; make -C PE-problem28 compall
problem29::; make -C PE-problem29 compall
problem30::; make -C PE-problem30 compall

problem31::; make -C PE-problem31 compall
problem32::; make -C PE-problem32 compall
problem33::; make -C PE-problem33 compall
problem34::; make -C PE-problem34 compall
problem35::; make -C PE-problem35 compall
problem36::; make -C PE-problem36 compall
problem37::; make -C PE-problem37 compall
problem38::; make -C PE-problem38 compall
problem39::; make -C PE-problem39 compall
problem40::; make -C PE-problem40 compall

problem41::; make -C PE-problem41 compall
problem42::; make -C PE-problem42 compall
problem43::; make -C PE-problem43 compall
problem44::; make -C PE-problem44 compall
problem45::; make -C PE-problem45 compall
problem46::; make -C PE-problem46 compall
problem47::; make -C PE-problem47 compall
problem48::; make -C PE-problem48 compall
problem49::; make -C PE-problem49 compall
problem50::; make -C PE-problem50 compall

problem51::; make -C PE-problem51 compall
problem52::; make -C PE-problem52 compall
problem55::; make -C PE-problem55 compall
problem56::; make -C PE-problem56 compall
problem57::; make -C PE-problem57 compall

problem63::; make -C PE-problem63 compall
problem65::; make -C PE-problem65 compall
problem69::; make -C PE-problem69 compall

problem71::; make -C PE-problem71 compall
problem73::; make -C PE-problem73 compall
problem75::; make -C PE-problem75 compall
problem80::; make -C PE-problem80 compall

problem92::; make -C PE-problem92 compall
problem94::; make -C PE-problem94 compall
problem97::; make -C PE-problem97 compall
problem100::; make -C PE-problem100 compall

problem104::; make -C PE-problem104 compall
problem108::; make -C PE-problem108 compall
problem110::; make -C PE-problem110 compall
problem145::; make -C PE-problem145 compall
problem157::; make -C PE-problem157 compall
problem162::; make -C PE-problem162 compall
problem164::; make -C PE-problem164 compall
problem169::; make -C PE-problem169 compall

problem301::; make -C PE-problem301 compall

######

srclines::
	wc -l PE-problem*/*.?ats

######

cleanall::
	make -C PE-problem1 cleanall
	make -C PE-problem2 cleanall
	make -C PE-problem3 cleanall
	make -C PE-problem4 cleanall
	make -C PE-problem5 cleanall
	make -C PE-problem6 cleanall
	make -C PE-problem7 cleanall
	make -C PE-problem8 cleanall
	make -C PE-problem9 cleanall
	make -C PE-problem10 cleanall
cleanall::
	make -C PE-problem11 cleanall
	make -C PE-problem12 cleanall
	make -C PE-problem13 cleanall
	make -C PE-problem14 cleanall
	make -C PE-problem15 cleanall
	make -C PE-problem16 cleanall
	make -C PE-problem17 cleanall
	make -C PE-problem18 cleanall
	make -C PE-problem19 cleanall
	make -C PE-problem20 cleanall
cleanall::
	make -C PE-problem21 cleanall
	make -C PE-problem22 cleanall
	make -C PE-problem23 cleanall
	make -C PE-problem24 cleanall
	make -C PE-problem25 cleanall
	make -C PE-problem26 cleanall
	make -C PE-problem27 cleanall
	make -C PE-problem28 cleanall
	make -C PE-problem29 cleanall
	make -C PE-problem30 cleanall
cleanall::
	make -C PE-problem31 cleanall
	make -C PE-problem32 cleanall
	make -C PE-problem33 cleanall
	make -C PE-problem34 cleanall
	make -C PE-problem35 cleanall
	make -C PE-problem36 cleanall
	make -C PE-problem37 cleanall
	make -C PE-problem38 cleanall
	make -C PE-problem39 cleanall
	make -C PE-problem40 cleanall
cleanall::
	make -C PE-problem41 cleanall
	make -C PE-problem42 cleanall
	make -C PE-problem43 cleanall
	make -C PE-problem44 cleanall
	make -C PE-problem45 cleanall
	make -C PE-problem46 cleanall
	make -C PE-problem47 cleanall
	make -C PE-problem48 cleanall
	make -C PE-problem49 cleanall
	make -C PE-problem50 cleanall
cleanall::
	make -C PE-problem51 cleanall
	make -C PE-problem52 cleanall
	make -C PE-problem55 cleanall
	make -C PE-problem56 cleanall
	make -C PE-problem57 cleanall
	make -C PE-problem63 cleanall
	make -C PE-problem65 cleanall
	make -C PE-problem69 cleanall
	make -C PE-problem71 cleanall
	make -C PE-problem73 cleanall
	make -C PE-problem75 cleanall
	make -C PE-problem80 cleanall
	make -C PE-problem92 cleanall
	make -C PE-problem94 cleanall
	make -C PE-problem97 cleanall
cleanall::
	make -C PE-problem100 cleanall
	make -C PE-problem104 cleanall
	make -C PE-problem108 cleanall
	make -C PE-problem110 cleanall
	make -C PE-problem145 cleanall
	make -C PE-problem157 cleanall
	make -C PE-problem162 cleanall
	make -C PE-problem164 cleanall
	make -C PE-problem169 cleanall
	make -C PE-problem301 cleanall

###### end of [Makefile] ######
