######

ATSCC=$(or $(ATSHOME), "/usr")/bin/atscc

######

checkall: compall cleanall
compall:: \
  problem1 \
  problem2 \
  problem3 \
  problem4 \
  problem5 \
  problem6 \
  problem7 \
  problem8 \
  problem9 \
  problem10 \
  problem12 \
  problem14 \
  problem16 \
  problem20 \
  problem25 \
  problem26 \
  problem33 \
  problem36 \
  problem48 \
  problem56 \
  problem57 \
  problem63 \
  problem65 \
  problem97 \
  problem145 \
  problem164 \
  problem169 \

######

problem1::; make -C PE-problem1 compall
problem2::; make -C PE-problem2 compall
problem3::; make -C PE-problem3 compall
problem4::; make -C PE-problem4 compall
problem5::; make -C PE-problem5 compall
problem6::; make -C PE-problem6 compall
problem7::; make -C PE-problem7 compall
problem8::; make -C PE-problem8 compall
problem9::; make -C PE-problem9 compall
problem10::; make -C PE-problem10 compall
problem12::; make -C PE-problem12 compall
problem14::; make -C PE-problem14 compall
problem16::; make -C PE-problem16 compall
problem20::; make -C PE-problem20 compall
problem25::; make -C PE-problem25 compall
problem26::; make -C PE-problem26 compall
problem33::; make -C PE-problem33 compall
problem36::; make -C PE-problem36 compall
problem48::; make -C PE-problem48 compall
problem56::; make -C PE-problem56 compall
problem57::; make -C PE-problem57 compall
problem63::; make -C PE-problem63 compall
problem65::; make -C PE-problem65 compall
problem97::; make -C PE-problem97 compall
problem145::; make -C PE-problem145 compall
problem164::; make -C PE-problem164 compall
problem169::; make -C PE-problem169 compall

######

cleanall::
	make -C PE-problem1 cleanall
	make -C PE-problem2 cleanall
	make -C PE-problem3 cleanall
	make -C PE-problem4 cleanall
	make -C PE-problem5 cleanall
	make -C PE-problem6 cleanall
	make -C PE-problem7 cleanall
	make -C PE-problem8 cleanall
	make -C PE-problem9 cleanall
	make -C PE-problem10 cleanall
	make -C PE-problem12 cleanall
	make -C PE-problem14 cleanall
	make -C PE-problem16 cleanall
	make -C PE-problem20 cleanall
	make -C PE-problem25 cleanall
	make -C PE-problem26 cleanall
	make -C PE-problem33 cleanall
	make -C PE-problem36 cleanall
	make -C PE-problem48 cleanall
	make -C PE-problem56 cleanall
	make -C PE-problem57 cleanall
	make -C PE-problem63 cleanall
	make -C PE-problem65 cleanall
	make -C PE-problem97 cleanall
	make -C PE-problem145 cleanall
	make -C PE-problem164 cleanall
	make -C PE-problem169 cleanall

###### end of [Makefile] ######
