all:: ATS tutorial example implementation resource library paper changelog

ATS::
	scp ATS.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/ATS.html

FAQ::
	scp FAQ.txt \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/FAQ.txt

tutorial::
	scp TUTORIAL/tutorial.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/TUTORIAL/tutorial.html

example::
	scp EXAMPLE/example.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/EXAMPLE/example.html

example_new::
	scp EXAMPLE/example_new.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/EXAMPLE/example_new.html

implementation::
	scp IMPLEMENTATION/implementation.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/IMPLEMENTATION/implementation.html

resource::
	scp RESOURCE/resource.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/RESOURCE/resource.html

library::
	scp LIBRARY/library.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/LIBRARY/library.html

paper::
	scp PAPER/paper.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/PAPER/paper.html

changelog::
	scp CHANGELOG/changelog.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/CHANGELOG/changelog.html

######

sysprog::
	scp BOOK/sysprog.html \
          ats-hwxi@web.sourceforge.net:/home/groups/a/at/ats-lang/htdocs/DOCUMENTATION/sysprog.html

###### end of [Makefile] ######
