#
#
# Makefile for some K&R examples
#
#

######

.PHONY: all
all:: checkall

######

checkall:: \
  compall \
  Chapter01 Chapter02 Chapter03 Chapter04 Chapter05 Chapter06 Chapter07 Chapter08 

######

Chapter01::
	cd Chapter01; make html

Chapter02::
	cd Chapter02; make html

Chapter03::
	cd Chapter03; make html

Chapter04::
	cd Chapter04; make html

Chapter05::
	cd Chapter05; make html

Chapter06::
	cd Chapter06; make html

Chapter07::
	cd Chapter07; make html

Chapter08::
	cd Chapter08; make html

######

compall:
	cd Chapter01; make all
	cd Chapter02; make all
	cd Chapter03; make all
	cd Chapter04; make all
	cd Chapter05; make all
	cd Chapter06; make all
	cd Chapter07; make all
	cd Chapter08; make all

######

cleanall:
	cd Chapter01; make cleanall
	cd Chapter02; make cleanall
	cd Chapter03; make cleanall
	cd Chapter04; make cleanall
	cd Chapter05; make cleanall
	cd Chapter06; make cleanall
	cd Chapter07; make cleanall
	cd Chapter08; make cleanall

###### end of [Makefile]

