/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2009-9-13: 19h:45m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_types.h"
#include "ats_basics.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/slseg.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologue from statically loaded files */
/* external codes at top */
/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
extern ats_void_type atspre_print_newline () ;
extern ats_void_type atspre_print_string (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_TERMINATION_CHECK
#endif /* _ATS_TERMINATION_CHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */

/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/fac2/hwxi/research/ATS/IMPLEMENT/Geizella/Anairiats/svn/ats-lang/doc/EXAMPLE/INTRO/HelloWorld.dats: 82(line=4, offs=16) -- 140(line=6, offs=4)
*/
ats_void_type
mainats () {
/* local vardec */
ATSlocal_void (tmp0) ;
ATSlocal_void (tmp1) ;

__ats_lab_mainats:
/* tmp1 = */ atspre_print_string ("Hello, world!") ;
/* tmp0 = */ atspre_print_newline () ;
return /* (tmp0) */ ;
} /* end of [mainats] */

/* static load function */

static int _2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__staload_flag = 0 ;

ats_void_type _2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__staload () {
if (_2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__staload_flag) return ;
_2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__staload_flag = 1 ;
return ;
} /* staload function */
/* dynamic load function */

// (external) dynload flag declaration
// extern int
// _2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__dynload_flag ;

ats_void_type
_2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__dynload () {
// _2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__dynload_flag = 1 ;
_2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__staload () ;
#ifdef _ATS_TERMINATION_CHECK
#endif /* _ATS_TERMINATION_CHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

int main (int argc, char *argv[]) {
ATS_GC_INIT() ;
mainats_prelude() ;
_2usr_2local_2share_2atshome_2doc_2EXAMPLE_2INTRO_2HelloWorld_2edats__dynload() ;
mainats((ats_int_type)argc, (ats_ptr_type)argv) ;
return (0) ;
} /* end of main */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [HelloWorld_dats.c] */
